### ISSUE TITLE
Self-referential many-to-many relationships are not supported

### ISSUE THREAD

**Issue by poteboy** [BriefHQ/drizzle-zero#29]
When trying to define a self-referential many-to-many relationship (e.g., user-to-user friendship), the type system throws an error.

```ts
// Drizzle schema
export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
})
export const friendship = pgTable(
  'friendship',
  {
    requestingId: text('requesting_id')
      .notNull()
      .references(() => user.id),
    acceptingId: text('accepting_id')
      .notNull()
      .references(() => user.id),
    accepted: boolean('accepted').notNull(),
  },
  (t) => [primaryKey({ columns: [t.requestingId, t.acceptingId] })]
)
// Zero schema - This causes a type error
export const schema = createSchema(
  createZeroSchema(drizzleSchema, {
    version: 1,
    tables: {
      user: {
        id: true,
        name: true,
      },
      friendship: {
        requesting_id: true,
        accepting_id: true,
        accepted: true,
      },
    },
    manyToMany: {
      user: {
        friends: ['friendship', 'user'], // Type error here
      },
    },
  })
)
.
```

**Comment by 0xcadams** [comment]
Hey @poteboy, let me take a look at this and get this resolved.

**Comment by 0xcadams** [comment]
This is resolved in `0.2.3`.

**Comment by poteboy** [comment]
@0xcadams Wow, thank you for the quick response! 🙌

**Comment by poteboy** [comment]
Sorry to bother you, but I updated to the latest version, and it seems the issue still isn’t resolved. Would it be possible for you to take a look and see where the problem might be? @0xcadams  cc @natew 

```ts
export const user = pgTable('user', {
  id: text('id').primaryKey(),
  username: text('username').notNull(),
  email: text('email').notNull(),
  name: text('name').notNull(),
  image: text('image'),
  state: json('state').$type<UserState>(),
  updatedAt: timestamp('updated_at'),
  createdAt: timestamp('created_at'),
})

export const friendship = pgTable(
  'friendship',
  {
    requestingId: text('requesting_id')
      .notNull()
      .references(() => user.id),
    acceptingId: text('accepting_id')
      .notNull()
      .references(() => user.id),
    accepted: boolean('accepted').notNull(),
    createdAt: timestamp('created_at'),
  },
  (t) => [primaryKey({ columns: [t.requestingId, t.acceptingId] })]
)

export const schema = createSchema(
  createZeroSchema(drizzleSchema, {
    version: 1,
    tables: {
      user: {
        id: true,
        username: true,
        email: true,
        name: true,
        image: true,
        state: true,
        updated_at: true,
        created_at: true,
      },
      server: {
        id: true,
        name: true,
        creator_id: true,
        channel_sort: true,
        description: true,
        icon: true,
        created_at: true,
      },
      channel: {
        id: true,
        server_id: true,
        name: true,
        description: true,
        private: true,
        created_at: true,
      },
      message: {
        id: true,
        server_id: true,
        channel_id: true,
        thread_id: true,
        is_thread_reply: true,
        creator_id: true,
        replying_to_id: true,
        content: true,
        created_at: true,
        updated_at: true,
        deleted: true,
      },
      attachment: {
        id: true,
        user_id: true,
        message_id: true,
        channel_id: true,
        type: true,
        data: true,
        url: true,
        created_at: true,
      },
      role: {
        id: true,
        name: true,
        color: true,
        server_id: true,
        creator_id: true,
        can_admin: true,
        can_edit_channel: true,
        can_edit_server: true,
        updated_at: true,
        created_at: true,
      },
      user_role: {
        server_id: true,
        user_id: true,
        role_id: true,
        granter_id: true,
        created_at: true,
      },
      channel_permission: {
        id: true,
        server_id: true,
        channel_id: true,
        role_id: true,
        granter_id: true,
        created_at: true,
      },
      pin: {
        id: true,
        server_id: true,
        channel_id: true,
        message_id: true,
        creator_id: true,
        created_at: true,
      },
      friendship: {
        requesting_id: true,
        accepting_id: true,
        accepted: true,
        created_at: true,
      },
      server_member: {
        server_id: true,
        user_id: true,
        joined_at: true,
      },
      thread: {
        id: true,
        channel_id: true,
        creator_id: true,
        message_id: true,
        title: true,
        deleted: true,
        description: true,
        created_at: true,
      },
      message_reaction: {
        message_id: true,
        creator_id: true,
        reaction_id: true,
        created_at: true,
        updated_at: true,
      },
      reaction: {
        id: true,
        value: true,
        keyword: true,
        created_at: true,
        updated_at: true,
      },
    },
    manyToMany: {
      user: {
        servers: ['server_member', 'server'],
        roles: ['user_role', 'role'],
      },
      server: {
        members: ['server_member', 'user'],
      },
      role: {
        members: ['user_role', 'user'],
      },
      channel: {
        roles: ['channel_permission', 'role'],
      },
      message: {
        reactions: ['message_reaction', 'reaction'],
      },
    },
  })
)
```

**Comment by 0xcadams** [comment]
Here's an example of how to use this: https://github.com/BriefHQ/drizzle-zero/blob/main/tests/schemas/many-to-many-extended-config.zero.ts

**Comment by poteboy** [comment]
@0xcadams 
Thank you for the example, it helps a lot!
I updated to version 0.2.3 and prepared a minimum reproduction using the [many-to-many-self-referential.schema.ts](https://github.com/BriefHQ/drizzle-zero/blob/main/tests/schemas/many-to-many-self-referential.schema.ts) and [many-to-many-self-referential.zero.ts](https://github.com/BriefHQ/drizzle-zero/blob/main/tests/schemas/many-to-many-self-referential.zero.ts) you created.

However, it seems the error is still occurring. I’m sorry to take up your time, but I’d appreciate it if you could take a look 🙏

https://github.com/poteboy/drizzle-zero-many-to-many-minimum-reproduction

**Comment by 0xcadams** [comment]
Thank you for the repro! The types are now simplified a bit and this should now be resolved in `0.2.4`. Please let us know if you have any other issues.
