### ISSUE TITLE
Types don't flow through with generative CLI

### ISSUE THREAD

**Issue by austinm911** [BriefHQ/drizzle-zero#71]
see https://github.com/BriefHQ/drizzle-zero/pull/66#issuecomment-2816461309

Reproduction Link: https://github.com/austinm911/drizzle-zero-monorepo

Reproduction
1. Create a drizzle schema with types defined in-file or outside of the file and passed to `$type`
2. Generate schema, check the file to see if the types pass through

![Image](https://github.com/user-attachments/assets/22bc5a6f-dc47-4dfe-908d-ebe97fe9b9ff)

**Comment by 0xcadams** [comment]
Can you provide a simple repro here? I would try using the `-t <tsconfig_file>` parameter.

We have a setup like this internally, where we have a `packages/core` package that holds our types, and it is working for us. It is likely that typescript can't resolve those types since the files aren't included in the tsconfig.

**Comment by 0xcadams** [comment]
I was able to reproduce this and put in a fix here: #73. Will be release in 0.8.4 - let me know if that fixes this issue!

**Comment by 0xcadams** [comment]
Closing but please re-open if you see more issues here.

**Comment by austinm911** [comment]
Cool, thanks for working through this. I think I can isolate one more remaining issue when the types are defined in the same. schema file. It seems to break when interfaces are defined in the same file. Using types over interfaces in the same file, it seems to generate fine.

Repro: https://github.com/austinm911/drizzle-zero-monorepo

```ts
// Define interface, pass to options
interface OptionsTwo {
    name: string
}

// Define type in line
export const tableTwo = p.pgTable('table_two', {
    id: p.varchar('id').primaryKey(),
    // This breaks the schema generation
    options: p.json('options').$type<OptionsTwo>(),
})
```

```bash
⚙️  Generating zero schema from ./src/schema/zero-config.ts...
/Users/am/Coding/repro/drizzle-zero-monorepo/node_modules/.pnpm/drizzle-zero@0.8.5_@rocicorp+zero@0.18.2025040300_drizzle-orm@0.38.4_@opentelemetry+api_98d9b9e2d68d99d17410a6795a404662/node_modules/drizzle-zero/dist/bin.cjs:277420
    throw new Error(
          ^

Error: ❌ drizzle-zero: Failed to find type definitions for zero-config.d.ts
    at getZeroSchemaDefsFromConfig (/Users/am/Coding/repro/drizzle-zero-monorepo/node_modules/.pnpm/drizzle-zero@0.8.5_@rocicorp+zero@0.18.2025040300_drizzle-orm@0.38.4_@opentelemetry+api_98d9b9e2d68d99d17410a6795a404662/node_modules/drizzle-zero/dist/bin.cjs:277420:11)
```

**Comment by 0xcadams** [comment]
Awesome, thanks for getting this repro. Let me take a look.

**Comment by 0xcadams** [comment]
So it looks like this is resolved by exporting the type:

```tsx
export interface OptionsTwo {
    name: string
}
```

**Comment by austinm911** [comment]
@0xcadams ah - that would make sense. Okay good to know. thanks

on another note noticing that there's an index signature when using the zero type helpers. Is this expected? I can create another issue to track.

<img width="1718" alt="Image" src="https://github.com/user-attachments/assets/01c65bbb-435c-4207-ad5e-2d69f8a95ab0" />

When viewing the InsertValue/UpdateValue helper on the mono app

<img width="1224" alt="Image" src="https://github.com/user-attachments/assets/16f04dda-5bf8-4459-819a-fa77e8ea1a85" />

**Comment by 0xcadams** [comment]
https://github.com/BriefHQ/drizzle-zero/pull/81

Both of these issues should be resolved with this latest PR and in 0.8.6.

**Comment by saturnonearth** [comment]
I am still getting this error, despite exporting the `types`

**Comment by saturnonearth** [comment]
I am still experiencing this error on `0.9.0` and I am exporting types.

**Comment by saturnonearth** [comment]
Ah nevermind it was something to do with old node modules - apologies!

**Comment by 0xcadams** [comment]
Cool - we simplified the workflow significantly so it shouldn't have any custom compilation step anymore and should simply import the custom types you define. Let me know if you have any other issues
